default_options: &default_options
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

mtgjson_options: &mtgjson_options
  <<: *default_options
  database_tasks: false
  prevent_writes: true
  database: db/mtgjson.sqlite

development:
  primary:
    <<: *default_options
    database: db/development.sqlite
  mtgjson:
    <<: *mtgjson_options

test:
  primary:
    <<: *default_options
    database: db/test.sqlite
  mtgjson:
    <<: *mtgjson_options
