default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "postgres" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASS") { "postgres" } %>
  database: <%= ENV.fetch("DB_NAME") { "mtgcollector" } %>

development:
  <<: *default
  database: mtgcollector_dev

test:
  <<: *default
  database: mtgcollector_test

production:
  <<: *default
