default_options: &default_options
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

mtgjson_options: &mtgjson_options
  <<: *default_options
  database_tasks: false
  prevent_writes: true
  database: mtgjson

development:
  primary:
    <<: *default_options
    database: mtgcollector_dev
  mtgjson:
    <<: *mtgjson_options

test:
  primary:
    <<: *default_options
    database: mtgcollector_test
  mtgjson:
    <<: *mtgjson_options
