default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { nil } %>
  password: <%= ENV.fetch("DB_PASS") { nil } %>

development:
  <<: *default
  database: mtgcollector

test:
  <<: *default
  database: mtgcollector_test
