name: "Continuous Integration"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/standardrb --no-fix --format github
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rails db:setup
        env:
          RAILS_ENV: test
      - run: bin/rails mtgjson:fetch
      - run: mv tmp/mtgjson.sqlite db/mtgjson.sqlite
      - run: bin/rspec --format RSpec::Github::Formatter
