name: "Continuous Integration"
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  analyze:
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/standardrb --no-fix --format github
  rspec:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rails db:setup
        env:
          RAILS_ENV: test
      - run: bin/rspec --format RSpec::Github::Formatter
